#!/bin/sh

f1=`mktemp -u /tmp/i3lock.XXXXXX.png`
f2=`mktemp -u /tmp/i3lock.XXXXXX.png`
ffmpeg -f x11grab -video_size 1680x1050 -i $DISPLAY -vframes 1 $f1
convert $f1 -blur 5x5 $f2
i3lock -i $f2
rm $f1 $f2
